### ISSUE TITLE
Sprachvariablen nicht sichtbar

### ISSUE THREAD

**Issue by yvseiler** [ilub-unibe-ch/ShortLink#5]
**Describe the bug**
Es fehlen die richtigen Sprachvariablen. Leider führt die Aktion "Sprache neu laden" zu keiner Veränderung. Es werden nach wie vor die Sprachschnippsel (z.B. -ui_uihk_ilubmod_title-) angezeigt.
 
**To Reproduce**
1. Go to 'Administration > ILIAS erweitern > Shortlink > Aktionen > Konfigurieren'
 
**Expected behavior**
Lesbare Sprachvariablen :)
 
**Screenshots**
<img width="675" alt="Bildschirmfoto 2023-11-30 um 08 33 40" src="https://github.com/ilub-unibe-ch/ShortLink/assets/30409415/19d2313c-743c-4857-8302-db0b719d4172">

**Comment by okaufman** [comment]
gefixt

**Comment by yvseiler** [comment]
Testfall ist nun "passed", vielen Dank.
