### ISSUE TITLE
Bearbeiten und Löschen eines Shortlinks führt zu Error

### ISSUE THREAD

**Issue by yvseiler** [ilub-unibe-ch/ShortLink#6]
**Describe the bug**
Klicke ich auf "Aktionen > Bearbeiten" eines bestehenden Shortlinks erhalte ich folgende Fehlermeldung:

TypeError thrown with message "ilObjShortLink::readSingleEntry(): Argument #1 ($id) must be of type int, string given, called in /var/www/ilias-next/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ShortLink/classes/class.ilShortLinkGUI.php on line 202"

Stacktrace:
#12 TypeError in /var/www/ilias-next/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ShortLink/classes/class.ilObjShortLink.php:93
#11 ilObjShortLink:readSingleEntry in /var/www/ilias-next/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ShortLink/classes/class.ilShortLinkGUI.php:202
#10 ilShortLinkGUI:edit in /var/www/ilias-next/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ShortLink/classes/class.ilShortLinkGUI.php:71
#9 ilShortLinkGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:199
#8 ilCtrl:forwardCommand in /var/www/ilias-next/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ShortLink/classes/class.ilShortLinkConfigGUI.php:49
#7 ilShortLinkConfigGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:199
#6 ilCtrl:forwardCommand in /var/www/ilias-next/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:162
#5 ilObjComponentSettingsGUI:forwardConfigGUI in /var/www/ilias-next/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:119
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /var/www/ilias-next/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /var/www/ilias-next/ilias.php:24

Gleiche Fehlermeldung erscheint, wenn ich bei einem Shortlink auf "Aktionen > Löschen" klicke.
 
**To Reproduce**
1. Go to 'Administration > ILIAS erweitern > Shortlink > Aktionen > Konfigurieren > Bestehender Shortlink > Aktionen > Bearbeiten' oder "Aktionen > Löschen2
 
**Expected behavior**
Formular zum Bearbeiten der Shortlink-Felder
 
**Screenshots**
<img width="1512" alt="Bildschirmfoto 2023-11-30 um 09 54 21" src="https://github.com/ilub-unibe-ch/ShortLink/assets/30409415/76ac7b70-c137-4d6b-8f7f-1251a7819369">

**Comment by okaufman** [comment]
gefixt

**Comment by yvseiler** [comment]
funktioniert korrekt, Testcase ist passed
