### ISSUE TITLE
Löschen Shortlink: Irritierende Success-Meldung

### ISSUE THREAD

**Issue by yvseiler** [ilub-unibe-ch/ShortLink#7]
**Problem**
Wird ein Shortlink gelöscht, wird als Erfolgsmeldung danach folgendes angezeigt:
"Nachdem der ShortLink gespeichert wurde, kann über www.yourILIASserver.ch/link/"yourShortLink" darauf zugegriffen werden."

Das Löschen hat also keine eigene Erfolgsmeldung, sondern zeigt dieselbe an wie nach dem "Aktualisieren".

**Procedure**
1. Öffne Shortlink plugin > Konfigurieren
2. Klicke neben einem bestehenden Shortlink auf "Aktionen" > "Löschen".
3. Bestätige mit "Löschen".

**Expected Results**
Ich würde eine Meldung erwarten wie sonst in ILIAS à la "Shortlink gelöscht".

**prio**
niedrig

![Bildschirmfoto 2024-03-20 um 16 34 46](https://github.com/ilub-unibe-ch/ShortLink/assets/30409415/c9ce01ad-f80c-4d18-a502-d5e06980d754)

**Comment by okaufman** [comment]
Jetzt werden beide Meldungen angezeigt
